### ISSUE TITLE
Not working in the iOS Simulator

### ISSUE THREAD

**Issue by williambout** [abhibeckert/Speed-Limit#1]
Is this supposed to be working in the iOS Simulator ?
I used the Freeway Drive simulation for location, but current speed in not displayed.

**Comment by abhibeckert** [comment]
My server doesn't have enough disk space to store all of open street map, I've only got map data for australia.

There are targets in the project that will convert an open street map xml file into the custom binary format used by this app, and you can place it on your own server.

**Comment by williambout** [comment]
Thanks for the reply.

**Comment by williambout** [comment]
Unfortunately, speed limit coverage is very low in California.
![screenshot](http://i.imgur.com/8lAxfwH.png)

I was hoping to get the current speed working, without the limit speed indicator.

**Comment by abhibeckert** [comment]
It will definitely show your current speed, I use the app all the time.

Just run it on your device. The simulator doesn't work well for geolocation.

If it doesn't work let me know, perhaps I have uncommmited changes.

Also a quick modification could set a fixed speed limit if you find the coverage is no good in your area - just hard code a speed limit whenever a search of your database returns 0.

4% coverage might not be too bad - since it will be the most commonly driven 4% of roads in your state.

**Comment by abhibeckert** [comment]
Actually, turns out I had some changes from several months ago that I never pushed up to github (nobody is using the app except for me).

It was totally broken on iOS 8 without them. Grab the latest code and it should work for you. :-)

**Comment by williambout** [comment]
Thanks you very much Abhi. It works in the simulator now :)
Unfortunately, I can't run it on my iPhone since I'm not a member of the iOS dev program, and my phone is not jailbroken.

**Comment by abhibeckert** [comment]
Email your device UDID to me (abhi@abhibeckert.com) and I'll send you a build that will work on your device.

You can find your UUID in iTunes when it's plugged in, just go to the summery tab for your device, click on "serial number" to change it to "udid" then right click on the UDID and copy it.

Also email/dropbox/etc the SLD files for the area area you want to drive in to test the app so I can upload them to my server.

**Comment by williambout** [comment]
Sent.
